language: python
services: sqlite
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
matrix:
    include:
      - python: 3.6
        env: TOX_ENV=py36-django111


script: tox -e $TOX_ENV

install:
    - pip install pip setuptools wheel -U
    - pip install tox
